---
- name: Configure Syslog Server IPs Play
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars_files:
   - groupslogssrv.yml

  tasks:
    - name: Collect Existing Syslog Configs
      ios_command:
        commands: show run | include logging host
      register: raw_sys_list
    
    - name: Parse the Existing Syslog Server IP raw_sys_list
      set_fact:
        parsed_syslog_list: "{{raw_sys_list.stdout[0].split() | ipaddr('address')}}"

    - name: Print Collected Configuration
      debug:
        msg: "{{parsed_syslog_list}}"

    - name: Logging Servers IPs 
      ios_config:
        lines:
          - logging host {{item}}  
        save_when: changed
      loop: "{{syslog_server}}" 
... 