---
stages:
  - syntax_validation
  - input_validation
  - deploy

yamllint_validation:
  stage: syntax_validation
  script:
    - yamlint group_var.yml
    - yamlint syslog.yml
    - yamlint syslog01.yml
    - yamlint syslog02.yml
    - yamlint sysaddverify.yml
    - yamlint syslogparse.yml
validate_input:
  stage: input_validation
  script:
    - ansible-playbook syslog.yml

deploy_syslog:
  stage: deploy
  only: 
   refs:
     - master
  
  script:
    - ansible-playbook syslog.yml -i inventory
...