---
stages:
  - syntax_validation
  - input_validation
  - deploy

yamllint:
  stage: syntax_validation
  script:
    - ansible --version
    - ansible-playbook syslog01.yml -i inventory  --syntax-check
    - ansible-playbook syslog02.yml -i inventory  --syntax-check
    - ansible-playbook syslogaddverify.yml -i inventory  --syntax-check
    - ansible-playbook syslogparse.yml -i inventory  --syntax-check
validate_input:
  stage: input_validation
  script:
    - ansible-playbook syslogparse.yml

deploy_syslog:
  stage: deploy
  only:
    refs:
      - master
  script:
    - ansible-playbook syslog01.yml -i inventory
...
