---
stages:
  - syntax_validation
  - input_validation
  - deploy

yamllint:
  stage: syntax_validation
  script:
    - yamlint groupslogssrv.yml
    - yamlint syslogaddverify.yml
validate_input:
  stage: input_validation
  script:
    - ansible-playbook syslogparse.yml
deploy_syslog:
  stage: deploy
  only:
    refs:
      - master
  script:
    - ansible-playbook syslog.yml -i inventory
...
